infer_dataset:
  - "/home/strage/flight_airsim_image/sequence8"

csv_name: "data_list.csv"

radian_weights_top_directory: "/home/strage/verify_for_SI2022_log/num_regression/train_log_2022_0904/"
radian_weights_file_name: "param_rad.pth"

infer_log_top_directory: "/home/strage/verify_for_SI2022_log/num_regression/train_log_2022_0904/"
radian_infer_log_file_name: "frame_infer_relust_radian.csv"

resize: 224
mean_element: 0.5
std_element: 0.5
dropout_rate: 0.0