
infer_dataset_top_directory: "/home/ssd_dir/flight_airsim_image/sequence8"
infer_dataset:
  - "/home/ssd_dir/flight_airsim_image/sequence8"

csv_name: "data_list.csv"

weights_top_directory: "/home/ssd_dir/verify_for_SI2022_log/train_log_2022_0826/"
weights_file_name: "weights.pth"

infer_log_top_directory: "/home/ssd_dir/verify_for_SI2022_log/train_log_2022_0826/"
infer_log_file_name: "frame_infer_relust.csv"

yaml_name: "infer_config.yaml"

index_dict_name: "index_dict_-30_30_range_step1deg.csv"

index_csv_path: "/home/pycode/attitude_estimator_in_timesformer/index_dict/index_dict_-30_30_range_step1deg.csv"

hyperparameters:
  img_size: 224
  resize: 224
  num_classes: 63
  deg_threshold: 30
  mean_element: 0.5
  std_element: 0.5
  dropout_rate: 0.0
  do_white_makeup: False
  do_white_makeup_from_back: False
  whiteup_frame: 0